[package]
name = "egor00f/2d-adventure"

description = "Egnine for 2d games in roblox"

version = "0.6.2"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github/Ukuroks-Games/2d-adventure"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

private = false

[dependencies]
giflib = "egor00f/giflib@>=0.4.5"
stdlib = "egor00f/stdlib@>=0.1.26"
cooldown = "egor00f/cooldownlib@>=0.1.4"
InputLib = "egor00f/inputlib@>=0.2.3"
[server-dependencies]


[dev-dependencies]
dialoglib = "egor00f/dialoglib@>=0.2.0"
testlib = "egor00f/testlib@>=1.0.1"
audioAnalyser="egor00f/audio-ui-analyser@>=0.1.0"


[place]
shared-packages = "game.ReplicatedStorage.Packages"
