[package]
name = "egor00f/2d-adventure"

description = "Egnine for 2d adventure games"

version = "0.1.0"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github/Ukuroks-Games/2d-adventure"

authors = ["Egor00f <velikiydolbayeb@gmail.com>"]

exclude = ["*"]

include = ["src", "src/**", "wally.toml", "README.md", "init.lua"]

private = false

[dependencies]
giflib = "egor00f/giflib@0.1.7"
stdlib = "egor00f/stdlib@0.1.8"
switch = "egor00f/switch@0.1.0"

[server-dependencies]


[dev-dependencies]
